### ISSUE TITLE
Renew SSL Certificate

### ISSUE THREAD

**Issue by PelinSmines** [DPGAlliance/publicgoods-scripts#216]
When clicking to https://digitalpublicgoods.net/submission, I receive the “This connection isn’t private” warning due to expired certificate.
We need to renew the SSL certificate. 
@ricardomiron

**Comment by ricardomiron** [comment]
The domain has a valid SSL certificate, this might be an issue regarding how this redirection was set up. Will investigate.

**Comment by gazdagergo** [comment]
We see this error message on proceeding at the end of eligibility form, that looks like certification error while posting to https://submission.digitalpublicgoods.net/api/saveDB/6f44a1cb-4c0f-44a8-8953-528506c594d2

![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/8988279/a6e3f33a-8bc7-4b9b-bc1d-c768dad01383)

**Comment by law909** [comment]
submission.digitalpublicgoods.net was an empty subdomain on the original server, so I did not moved it to the new server. @gazdagergo the error message you see was because of that.

Now I created submission.digitalpublicgoods.net on the server which redirects the user to app.digitalpublicgoods.net.
digitalpublicgoods.net/submission redirects to submission.digitalpublicgoods.net which is working now.

I think this issue can be closed, @PelinSmines  please try https://digitalpublicgoods.net/submission, it should redirect you to https://app.digitalpublicgoods.net/signup (or your home page if you are logged in).

**Comment by gazdagergo** [comment]
**AC**

- navigate to the https://digitalpublicgoods.net/submission
- it will redirect you to the https://app.digitalpublicgoods.net/signup
