### ISSUE TITLE
[Registry Mobile][WP theme] Icon alignment

### ISSUE THREAD

**Issue by law909** [DPGAlliance/publicgoods-scripts#238]
Nomination, DPGA Technical Team Review and Digital Public Good steps should be displayed side by side instead of one by one scrolled way.

**Comment by law909** [comment]
Wordpress theme issue

**Comment by skylark1848** [comment]
Acceptance criteria

On URL https://digitalpublicgoods.net/registry/

Set screen size to mobile device such as iPhone SE. Icons "Nomination, DPGA Technical Team, Digital Public Good" should align horizontally next to each other on page.

![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/4942278/f360faf3-cb65-4281-bdb4-eb3f22aa8626)

**Comment by gazdagergo** [comment]
Suggestion: the icons visually are not centered because the non-justified text block above has no right edge. What if we add some space to the right of the bounding box of the icons to center them visually. I tested it and a right padding of 1rem looks good. 

![Image](https://github.com/DPGAlliance/publicgoods-scripts/assets/8988279/fafb21cd-4d27-42f9-95ff-6792538619c2)

**Comment by PelinSmines** [comment]
Looks good now.
