### ISSUE TITLE
Improve data visualization in registry section

### ISSUE THREAD

**Issue by edil-it-them** [DPGAlliance/publicgoods-scripts#8]
The current implementation of `distribution by type` diagram in [Registry section](https://digitalpublicgoods.net/registry/) uses circles. It is a bad pattern in data visualization. Let me explain.
When we visualize data with circles we need to calculate the area with weird for human mind formula A = πr², where A represents area (value of data), r - radius, π=3.1415. Because of r² and π it's hard for users to understand the dimensions and visually compare different circles.

Let's imagine a circle. Now try to imagine another one smaller twice.
Common answer is to reduce width(diameter) of circle twice, but it's wrong. 
![Frame 16](https://user-images.githubusercontent.com/44370635/116114906-7ca53480-a6c2-11eb-9711-b2f9ec02ee22.jpg)

I suggest to use rectangles instead. This is why:
![Frame 17](https://user-images.githubusercontent.com/44370635/116115329-f0dfd800-a6c2-11eb-92a5-779544dcca50.jpg)

**Current:**
![current type](https://user-images.githubusercontent.com/44370635/116101389-71e4a280-a6b6-11eb-8b3c-725ab36887df.PNG)

**Suggestion:** 
I suggest the following design. Note that dimensions are inaccurate.
![Frame 15](https://user-images.githubusercontent.com/44370635/116116171-8713fe00-a6c3-11eb-9cc0-48528dfa12d5.jpg)

**Even better**
Users don't need to hover if number fit the rectangle.
![Frame 15](https://user-images.githubusercontent.com/44370635/116115907-3bf9eb00-a6c3-11eb-9029-03ad07120373.jpg)

It will also better align with tree map design of `distribution by SDG` chart
I can see that visualization is rendered in this [repo](https://github.com/unicef/publicgoods-scripts/blob/master/index.js) so I opened issue here
@lacabra what do you think?

**Comment by lacabra** [comment]
Thanks @Rolikasi, I absolutely love it, thanks for your very detailed explanation, I very much appreciate your time to explain it so clearly. I am in full support of changing this visualization!

Are you still thinking of leaving the hovering in place? because I agree with you that is not needed if it fits within the rectangles above, but it is still useful to know where rectangles overlap (say how many nominees are labeled both software and data?)

**Comment by Rolikasi** [comment]
@lacabra, I'm happy to help! 
I agree that hovering is useful and we need to leave it in place.

**Comment by lacabra** [comment]
@Rolikasi I would love for you to cross this off your list in the coming month. I've given it some thought and realize that there is one more constraint that you should be aware off. The current display of `software`, `data`, `content` and `standard` is incomplete because we have a fifth type: `ai model`. This potentially creates a major issue, which is the impossibility of displaying an intersection between 5 sets given 4-side square figures, though I claim that there will never be one single DPG that can be all of 5 types at once. The most common overlap right now is between `software`, `data` and `content` which is a 3-way overlap, when we introduce `ai model` I think that will overlap with `data` and `software`, possibly with `content`.
